### PR TITLE
Revered to the custom parallax

### PR DESCRIPTION
**Pull request by winterpk**
I turned off parallax for mobile devices and tablets because it was too buggy.

### CODE REVIEW

**Comment by moveson** [comment]
OK, so no parallax on mobile--that's fine. Are the images displaying properly on iOS?

**Comment by winterpk** [comment]
Mark, yes the images are not zoomed in anymore on iOS. I think everything should be working as expected now.

IF we have anymore parallax issues, I have something else I can try which may make the animations a little smoother.

**Comment by moveson** [comment]
I just pushed up to production. Parallax still looks great on desktop and the photos are correct on my phone. Thank you!

**Comment by winterpk** [comment]
Awesome! Glad that worked out.

**Pull request merged**
