### PR TITLE
Voltage Work

### PR DESCRIPTION
**Pull request by legoabram**
Alright. Here are the quick fixes.

Personally, I think it would look a little too strange to have the pagination on the top of the table.

### CODE REVIEW

**Comment by moveson** [comment]
Looks great. Thanks so much!

**Comment by moveson** [comment]
Bug report: Discard All button does not seem to be working at all in Safari. Works fine in Chrome.

**Comment by moveson** [comment]
Discard All also does not work in Firefox. Maybe another ES6-related problem?

**Comment by legoabram** [comment]
Hmm... You may need to open up the console and send me any errors that it's making. What exactly isn't working? I just launched firefox and it appeared to be functional.

**Pull request merged**
