### PR TITLE
Rapid Mode Button Change

### PR DESCRIPTION
**Pull request by legoabram**
My phone died, sorry. Here is what I've done so far. The color can change, yellow was just one that already existed.

### CODE REVIEW

**Comment by moveson** [comment]
Nice work, Abram. The functionality is perfect. I can see two cosmetic issues that I'd like to change: 

1. If a time field is disabled, it would be nice if the Rapid Mode toggle was also disabled (to avoid confusion)

2. The race director asking for the changes would like to see an indication that times entered in the fields are times of day (as opposed to elapsed times from start). Could we add mouseover text to the fields or the field labels? Or would it make more sense to change the field labels to "Time of Day In" and "Time of Day Out"?

**Comment by moveson** [comment]
Also, I think the yellow is fine, but might be interesting to see what blue would look like for the background color.

**Comment by legoabram** [comment]
I'm not sure if it makes sense to disabled the toggle when a field is disabled. When switching to a split with a disabled out field, the time will persist even if the field is disabled. Now, the outline could be removed to indicate that rapid mode is disabled, but if it then turned back on when switching back to another split, that could cause more confusion. It could also just turn off the rapid mode for that field, but then it would have to be turned back on after switching to another split. Or, the outline could stay but the toggle is disabled, but that would look like the toggle is broken.

As for the time of day thing, I'm tempted to say that it seems a bit paranoid. Otherwise, "Time of Day" should be okay. As a passing thought, could something like... "Time In (24hr)" work?

For the blue background thing, sure.

**Comment by moveson** [comment]
As for the toggle, I'm not explaining myself very well. We don't need to change the value from enabled to disabled or back. I'd just like to make it so that toggle doesn't function if the field is greyed out. It might be confusing if someone clicks "Enable Rapid Mode" and sees the icon change, but then a time doesn't appear there when they enter a bib number.

Let's go with "Time In (24hr)" and "Time Out (24hr)".

**Comment by moveson** [comment]
Great stuff!

**Pull request merged**
