### PR TITLE
Travis continuous integration

### PR DESCRIPTION
**Pull request by cabello**
Travis is free for open source projects, it will run the spec for the project and report on failed tests.

### CODE REVIEW

**Comment by moveson** [comment]
This project uses Heroku CI/CD, so I don't think I want to introduce another CI solution unless there is a compelling reason to do so. Thoughts?

**Comment by cabello** [comment]
Can I check the results from Heroku CI, is there anything that is private there?

I agree it's not great to have multiple solutions to the same problem. An argument for Travis or any other CI that is free for Open Source projects is that it simplifies contribution by showing failures to newcomers when they open a new PR.

**Comment by moveson** [comment]
Heroku CI is tied to github and will run with any push to this repo. Would it get you to the same place if you were to create a branch on this repo and push to that branch? That would allow you to see test results. 

I'm open to considering Travis if that's not a good solution.

**Comment by cabello** [comment]
Oh yeah, I forgot to share the publicly accessible CI results https://travis-ci.com/cabello/OpenSplitTime

**Comment by cabello** [comment]
Build is now green! 💚 Going back on discussing CI/CD options what is Heroku CI doing? Is it also triggering the deployment?

**Comment by moveson** [comment]
This is all very interesting. Thanks for all the work to get this set up and passing on Travis. 

Heroku CI/CD works like this. A push to any branch triggers a new test run. If the push is to master, and if all tests pass, the build is automatically deployed to the [staging site](ost-stage.herokuapp.com). From there, we can optionally deploy the build to production. Because it's the same build, that deploy happens in just 10-20 seconds--just the time to copy the build to the production servers and run the release phase (migrations and such). This is very smooth and I'd like to keep that workflow. 

But given that Travis is free, and given that it will make life easier for collaborators, I see no issue with integrating it into the project. So I'll go ahead and merge the PR. 

Again, thanks for all your work on this, Danilo. Very much appreciated.

**Comment by moveson** [comment]
Could you also add something to the README about Travis CI to assist future collaborators?

**Comment by cabello** [comment]
Sure, I will try to get to it soon still this week.

**Pull request merged**
