### PR TITLE
Effort shows the state drop down

### LINKED ISSUE #32: Effort form: Fix state drop-down menu
OpenSplitTime uses the Carmen gem for country and state/subregion identification. The efforts form (`views/efforts/_form.html.erb`) contains form helpers intended to build country and state menus. The country menu is populated when the form is loaded, and the state menu is populated only if a country has been chosen; if no country is chosen, the state menu indicates 'Choose a country first.' All this is working properly.

When a country is chosen, the state menu should be populated with applicable states/subregions on the fly, but this is not currently working. Instead, when a country is chosen, the state menu remains unchanged, and when the user submits the form, the new effort is assigned to the first state associated with the chosen country (for the United States, it uses Alabama).

This was working properly at one time. It seems likely that the javascript that used to populate the state menu has ceased working or is not getting called.

Note that this same feature exists in the participant form (`views/participants/_form.html.erb`) and it works properly there.

### PR DESCRIPTION
**Pull request by nplasterer**
Fixes #32

Displays the correct state whenever a country is selected for efforts.

cc: @moveson

### CODE REVIEW

**Comment by moveson** [comment]
Just wondering when you might find time to finish this PR. Lots to do here if you have some capacity!

**Comment by nplasterer** [comment]
@moveson I definitely haven't forgotten about it. I have tomorrow and Friday off of work. I figured I'd try to sneak this in then.

**Comment by moveson** [comment]
Great. Thank you!

**Comment by nplasterer** [comment]
@moveson this is ready for your review.

**Comment by moveson** [comment]
Works great. Merged and will push to staging soon. Thank you!

**Pull request merged**
